# Generated by Django 2.0.4 on 2018-04-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('devicepsw', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(help_text='Enter username for account', max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Enter email for account', max_length=100)),
                ('password', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercontrols.User'),
        ),
    ]
